posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

# Views
urlpatterns = [

  path(
    route='',
    view=views.PostFeedView.as_view(),
    name='feed'
  ),
  path(
    route='posts/new/',
    view=views.CreatePostView.as_view(),
    name='create'
  ),
  path(
    route='<int:pk>',
    view=views.PostDetailView.as_view(),
    name='detail'
  )

]

pygram/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Local
from pygram import views as local_views
# Apps
from posts import views as posts_views
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),

    # Test views
    path('hello_world/', local_views.hello_word, name='hello_world'),
    path('sorted/', local_views.sorted_numbers, name='sort'),
    path('greetings/<str:name>/<int:age>', local_views.greetings, name='greetings'),

    # Posts views
    # url_module, app_name
    path('', include(('posts.urls', 'posts'), namespace='posts')),

    # Users views
    path('users/', include(('users.urls', 'users'), namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# Django
from django.urls import path
from django.views.generic import TemplateView

# Views
from users import views

urlpatterns = [
  # Posts
  #Managment
  path(
    'login/', 
    view=views.LoginView.as_view(),
    name='login'
  ),
  path(
    'logout/', 
    view=views.LogoutView.as_view(),
    name='logout'
  ),
  path(
    'signup/', 
    view=views.SignUpView.as_view(), 
    name='signup'
  ),
  path(
    'me/profile/',
    view=views.UpdateProfileView.as_view(), 
    name='update'
  ),
  path(
    route='<str:username>/',
    # Class-based view
    # view=TemplateView.as_view(template_name='users/detail.html'),
    view=views.UserDetailView.as_view(),
    name='detail'
  ),
]

templates/base.html
<!DOCTYPE html>
<htmllang="en">
<head>
  <metacharset="UTF-8">
  
  <!-- Header block -->
  {% block head_content %}
  {% endblock %}

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
  <!-- Py module to include another html file -->
  {% include "navbar.html" %}
  
  <div class="container mt-5">
    <!-- **block** defines an space where the code will be inserted -->
    <!-- Content or body block -->
    {% block container %}
    {% endblock %}
  </div>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
  <div class="container">

    <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
      <img src="{% static "assets/pygram.png" %}" height="45" class="d-inline-block align-top"/>
    </a>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <a href="{% url "users:detail" request.user.username %}">
            {% if request.user.profile.picture %}
              <img src="{{ request.user.profile.picture.url }}" width="35" height="35" class="d-inline-block align-top rounded-circle"/>
            {% else %}
              <img src="{% static 'assets/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
            {% endif %}
          </a>
        </li>

        <li class="nav-item nav-icon">
          <a href="{% url "posts:create" %}">
            <i class="fas fa-plus"></i>
          </a>
        </li>

        <li class="nav-item nav-icon">
          <a href="{% url "users:logout" %}">
            <i class="fas fa-sign-out-alt"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/pagination.html
<nav>
  <ul class="pagination justify-content-end">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
        Previous
      </a>
    </li>
    {% endif %}
    <li class="page-item">
      <a class="page-link" href="#">
        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </a>
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        Next
      </a>
    </li>
    {% endif %}
  </ul>
</nav>