posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

# Views
urlpatterns = [

  path(
    route='',
    view=views.PostFeedView.as_view(),
    name='feed'
  ),
  path(
    route='posts/new/',
    view=views.CreatePostView.as_view(),
    name='create'
  ),
  path(
    route='<int:pk>',
    view=views.PostDetailView.as_view(),
    name='detail'
  )

]

pygram/urls.py
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Local
from pygram import views as local_views
# Apps
from posts import views as posts_views
from users import views as users_views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),

    # Test views
    path('hello_world/', local_views.hello_word, name='hello_world'),
    path('sorted/', local_views.sorted_numbers, name='sort'),
    path('greetings/<str:name>/<int:age>', local_views.greetings, name='greetings'),

    # Posts views
    # url_module, app_name
    path('', include(('posts.urls', 'posts'), namespace='posts')),

    # Users views
    path('users/', include(('users.urls', 'users'), namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# Django
from django.urls import path
from django.views.generic import TemplateView

# Views
from users import views

urlpatterns = [
  # Posts
  #Managment
  path(
    'login/', 
    view=views.LoginView.as_view(),
    name='login'
  ),
  path(
    'logout/', 
    view=views.LogoutView.as_view(),
    name='logout'
  ),
  path(
    'signup/', 
    view=views.SignUpView.as_view(), 
    name='signup'
  ),
  path(
    'me/profile/',
    view=views.UpdateProfileView.as_view(), 
    name='update'
  ),
  path(
    route='<str:username>/',
    # Class-based view
    # view=TemplateView.as_view(template_name='users/detail.html'),
    view=views.UserDetailView.as_view(),
    name='detail'
  ),
]

users/models.py
''' Users models '''

# Django
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
  ''' Profile model 
  Proxy model that extends the base data with other information
  '''
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  website = models.URLField(max_length=256, blank=True)
  biography = models.TextField(blank=True,null=True)
  phone_number = models.CharField(max_length=16, blank=True)
  # BASE_DIR == MEDIA_URL (Only for media files)
  picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)
  modified = models.DateTimeField(auto_now=True)

  def __str__(self):
    ''' Return username '''
    return self.user.email

users/forms.py
"""" User forms """

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

class SignUpForm(forms.Form):
  """ Sign up form """
  username = forms.CharField(min_length=4,max_length=64)
  password = forms.CharField(max_length=64, widget=forms.PasswordInput())
  password_confirmation = forms.CharField(max_length=64, widget=forms.PasswordInput())

  first_name = forms.CharField(min_length=2,max_length=64)
  last_name = forms.CharField(min_length=2,max_length=64)
  email = forms.CharField(min_length=8,max_length=128,widget=forms.EmailInput())

  def clean_username(self):
    """ Username must be unique """
    username = self.cleaned_data['username']
    exist = User.objects.filter(username=username).exists() # True or False if exist

    if exist:
      raise forms.ValidationError('Username is already used')
    return username

  def clean(self):
    """ Verify password confirmation match """
    data = super().clean()

    password = data['password']
    password_confirmation = data['password_confirmation']

    if password != password_confirmation:
      raise forms.ValidationError('Password did not match')

    return data

  def save(self):
    data = self.cleaned_data
    data.pop('password_confirmation')

    user = User.objects.create_user(**data)
    profile = Profile(user=user)
    profile.save()


class ProfileForm(forms.Form):
  """ Profile form """

  website = forms.URLField(max_length=200, required=True)
  biography = forms.CharField(max_length=500, required=False)
  phone_number = forms.CharField(max_length=20, required=False)
  picture = forms.ImageField()

users/views.py
""" User views """

# Django
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout, views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse_lazy
# Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post
# Exceptions
from django.db.utils import IntegrityError
# Utils
from pdb import set_trace
# Forms
from users.forms import ProfileForm, SignUpForm

class LoginView(auth_views.LoginView):
  """ Login view """
  template_name = 'users/login.html'


def login_view(request):
  """ Login view """
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user:
      login(request,user)
      return redirect('posts:feed')
    else:
      return render(request, 'users/login.html', { 'error': 'Invalid username and password'})
  else:
    return render(request, 'users/login.html') # users/login.html


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
  """ Logout view """
  template_name = 'users/logout.html'


@login_required
def logout_view(request):
  """ Logout request """
  logout(request)
  return redirect('users:login')


class UserDetailView(DetailView):
  """ User detail view """
  template_name = 'users/detail.html'
  slug_url_kwarg = 'username'
  slug_field = 'username'
  queryset = User.objects.all()
  context_object_name='name'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    user = self.get_object()
    context['posts'] = Post.objects.filter(user=user).order_by('created')
    return context


class SignUpView(FormView):
  """ User signup view """

  template_name = 'users/signup.html'
  form_class = SignUpForm
  success_url = reverse_lazy('users:login')

  # Have to overwrite this to make an action once the form is validated
  def form_valid(self, form):
    """ Save form data """
    form.save()
    return super().form_valid(form)


# def signup_view(request):
#   """ Sign up view """
#   if request.method == 'POST':
#     form = SignUpForm(request.POST)
#     if form.is_valid():
#       form.save()
#       return redirect('login')
  
#   else:
#     form = SignUpForm()

#   return render(
#     request, 
#     'users/signup.html',
#     context={'form':form}
#   )

class UpdateProfileView(LoginRequiredMixin, UpdateView):
  """ Update profile view """

  template_name = 'users/update_profile.html'
  model = Profile
  fields = ['website', 'biography', 'phone_number', 'picture']

  def get_object(self):
    """ Return user's profile """
    return self.request.user.profile

  def get_success_url(self):
    """ Return to user's profile """
    username = self.object.user.username
    return reverse('users:detail', kwargs={'username': username})

# @login_required
# def update_profile(request):
#   """ Update a user's profile view """
#   user = request.user
#   profile = user.profile
#   if request.method == 'POST':
#     form = ProfileForm(request.POST, request.FILES) # In request.FILES is the multipart
#     if form.is_valid():
#       data = form.cleaned_data
#       profile.website = data['website']
#       profile.phone_number = data['phone_number']
#       profile.biography = data['biography']
#       profile.picture = data['picture']
#       profile.save()

#       url = reverse('users:detail', kwargs={'username': request.user.username})
#       return redirect(url)
#   else:
#     form = ProfileForm()

#   return render(
#     request, 
#     'users/update_profile.html',
#     {
#       'user': user,
#       'profile': profile,
#       'form':form
#     })

templates/users/base.html
<!DOCTYPE html>
<htmllang="en">
<head>
  <metacharset="UTF-8">
  {% block head_content %}{% endblock %}

  <!-- This literally load static files and give you access to it using static word -->
  {% load static %}
  <!-- Dependencies -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/ releases/v5.1.0/css/all.css" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">
  <div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5"id="auth-container">
        <img src="{% static "assets/pygram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

        {% block container %}{% endblock%}
      </div>
    </div>
  </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
      <div class="row">

        <div class="col-sm-4 d-flex justify-content-center">
          <img
            src="{{ user.profile.picture.url }}"
            alt="@{{ user.username }}"
            class="rounded-circle"
            height="150"
            width="150"
          />
        </div>

        <div class="col-sm-8">
          <h2 style="font-weight: 100;">
            {{ user.username }}
            {% if user == request.user %}
              <a
                href="{% url "users:update" %}" 
                class="ml-5 btn btn-sm btn-outline-info"
              >
                Edit profile
              </a>
            {% else %}
              <a
                href=""
                class="ml-5 btn btn-sm btn-primary"
              >
                Follow
              </a>
            {% endif %}
          </h2>

          <div class="row mt-2" style="font-size: 1.2em">
            <div class="col-sm-4">
              <b>{{ user.profile.posts_count }}785</b> posts
            </div>
            <div class="col-sm-4">
              <b>{{ user.profile.followers }}1,401</b> followers
            </div>
            <div class="col-sm-4">
              <b>{{ user.profile.following }}491</b> following
            </div>
          </div>
          <div class="row mt-4">
            <div class="col-sm-12">
              <p>{{ user.profile.biography }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
      <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
          <a href="{% url "posts:detail" post.id %}" class="border">
            <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
          </a>
        </div>
        {% endfor %}
      </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
  <title> Pygram sign in </title>
{% endblock %}

{% block container %}

  {% if form.errors %}
    <!-- .p.alert.alert-danger -->
    <!-- <p class="alert alert-danger">{{error}}</p> -->
    <p class="alert alert-danger">
      Your username and password didn't match. Please try again
    </p>
  {% endif %}
  <!-- Takes url's name to a normal url (names are declared in urls) -->
  <form method="POST" action="{% url "users:login" %}">
    <!-- Special token to make request -->
    {% csrf_token %} 

    <!-- .form-group>inpur.form-control -->
    <div class="form-group">
      <input type="text" placeholder="Username" name="username" class="form-control">
    </div>

    <div class="form-group">
        <input type="password" placeholder="Password" name="password" class="form-control">
    </div>
    
    <button class="button btn btn-primary btn-block mt-5" type="submit"> Sign in </button>
    
  </form>

  <p class="mt-4">
    Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here!</a>
  </p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
  <title> Sign Up </title>
{% endblock %}

{% block container %}
  {% if error %}
    <p class="alert alert-danger">{{ error }}</p>
  {% endif %}
  <form method="POST" action="{% url "users:signup" %}">
    {% csrf_token %}
    <!-- <div class="form-group">
      <input type="text" class="form-control" placeholder="Username" name="username" required>
    </div>
    <div class="form-group">
      <input type="password" class="form-control" placeholder="Password" name="password">
    </div>
    <div class="form-group">
      <input type="password" class="form-control" placeholder="Password confirmation" name="password_confirmation">
    </div>
    <div class="form-group">
      <input type="text" class="form-control" placeholder="First name" name="first_name" required>
    </div>
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Last name" name="last_name" required>
    </div>
    <div class="form-group">
      <input type="email" class="form-control" placeholder="Email address" name="email" required>
    </div> -->
    {{ form.as_p }}

    <button class="button btn btn-primary btn-block mt-5" type="submit"> Register </button>

  </form>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }}</title>
{% endblock %}

{% block container %}
  <div class="container">

    <div class="row justify-content-md-center">
      <div class="col-6 p-4" id="profile-box">

        <form action="{% url "users:update" %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- {% if form.errors %}
            <p class="alert alert-danger">{{ form.errors }}</p>
          {% endif %} -->

          <div class="media">
            {% if profile.picture %}
              <img src="{{ profile.picture.url }}" class="rounded-circle" height="75" width="75" />
            {% else %}
              <img src="{% static 'assets/default-profile.png' %}" class="rounded-circle" height="50" />
            {% endif %}

            <!-- Picture field  -->
            <div class="media-body">
              <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
              <p class="ml-4">
                <input type="file" name="picture">
              </p>
            </div>
          </div>

          {% for error in form.picture.errors %}
            <div class="alert alert-danger">
              <b> Picture: </b> {{ error }}
            </div>
          {% endfor%}

          <hr><br>

          <!-- Website field -->
          <div class="">
            <label>Website</label>
            <input
              class="form-control {% if form.website.errors %} is-invalid {% endif %}"
              name="website"
              placeholder="Website"
              value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
            />
            <div class="invalid-feedback">
              {% for error in form.website.errors %}
                {{ error }}
              {% endfor %}
            </div>
          </div>

          <!-- Biography field -->
          <div class="mt-3">
            <label>Biography</label>
            
            <textarea 
              class="form-control {% if form.biography.errors %} is-invalid {% endif %}"
              name="biography"
            >{% if form.errors %}{{form.biography.value}}{% else %}{{profile.biography}}{% endif %}</textarea>
            <div class="invalid-feedback">
              {% for error in form.biography.errors %}
                {{ error }}
              {% endfor %}
            </div>
          </div>


          <!-- Phone number field -->
          <div class="mt-3">
            <label>Phone number</label>
            <input
              class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
              name="phone_number"
              type="text"
              placeholder="Phone number"
              value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}""
            />
            <div class="invalid-feedback">
              {% for error in form.phone_number.errors %}
                {{ error }}
              {% endfor %}
            </div>
          </div>

          <button class="btn btn-primary btn-block mt-5" type="submit">Submit</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}